name: Mustache Pro Mod Menu Builder
on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build_job:
    runs-on: macos-14
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Compile and Zip Output
      run: |
        # تجميع ملف main.mm المحفوظ في مستودعك إلى dylib
        xcrun -sdk iphoneos clang++ -dynamiclib -arch arm64 -arch arm64e -miphoneos-version-min=14.0 -fobjc-arc main.mm -o MustacheMenu.dylib -framework UIKit -framework CoreGraphics -framework QuartzCore
        
        # ضغط الملف بصيغة zip ليتعرف عليه الجوال فوراً للتحميل
        zip MustacheMenu.zip MustacheMenu.dylib
        echo "تم تجميع وضغط الملف بنجاح!"

    - name: Upload Zip Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Download-AutoTouch-Zip
        path: MustacheMenu.zip
