TARGET := iphone:clang:latest:14.0
ARCHS := arm64

include $(THEOS)/makefiles/common.mk

TWEAK_NAME := Autotouh

Autotouh_FILES := main.mm
Autotouh_FRAMEWORKS := UIKit Foundation CoreGraphics

include $(THEOS_MAKE_PATH)/tweak.mk
